### ISSUE TITLE
Convert to SASS Module System 

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/tech-policy-database#13]
#### Description
Sass just launched its new feature, the module system. The system will replace the previously utilized @import rule and upgrade specific built-in functions. The existing Sass structure in this repo follows the old system. Refactor to follow Sass Module rules and utilize new functions. 

#### Tasks
- [x] Refactor to follow Sass Module rules and utilize new functions:
  - [x] Replace @import with @use rules
  - [x] Pass along files with @forward
  - [x] Import built-in Sass modules when necessary 

#### Additional Resources
- https://css-tricks.com/introducing-sass-modules/
- https://sass-lang.com/documentation/modules
