### ISSUE TITLE
Site Footer

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/tech-policy-database#14]
#### Description
When creating the Site Footer, make sure to utilize the site-information.json file. This will dynamically construct information from Forestry and will continue to update as the program makes changes to the data. 

#### Tasks
- [x] Methodology
- [x] Program Description
- [x] CSIS Logo (link to csis.org)
- [x] Copyright
- [x] ILab Source Information (link to iLab)
- [x] Contact Info
  - [x]  Website (csis.org)
  - [x] Address
