### ISSUE TITLE
Site Header 

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/tech-policy-database#15]
#### Description
When creating the Site Header, make sure to utilize the site-information.json file. This will dynamically construct information from Forestry and will continue to update as the program makes changes to the data. 

#### Tasks
- [x] CSIS Logo (link to csis.org)
- [x] Share Icons 
  - [x] Add icons
  - [x] Share Links (Include Text)
  - [x] Include necessary meta tags
- [x] Program Name
- [x] Title
- [x] Intro Paragraph
- [x] Methodology [jump link]
- [x] Download Data [CSV link]
