### ISSUE TITLE
Add Table Scroll Buttons

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/tech-policy-database#18]
#### Description
User should be able to scroll the table left or right by clicking on the icons.

#### Tasks
- [x] Add left and right arrow icons in TableOptions
- [x] Build arrow functionality:
  - [x] Clicking an arrow should scroll the table left or right by the width of a column (300px)
  - [x] Make mobile responsive
