### ISSUE TITLE
Table Header Cell

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/tech-policy-database#20]
#### Tasks
- [x] Framework Information:
  - [x]  Add info icon
  - [x]  Clicking on framework name or icon opens Members Modal
- [x] Organization:
  - [x]  Add organization to the parsed data object 
- [x] Original Document Link:
  - [x]  Add document link icon
