### ISSUE TITLE
Members Modal

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/tech-policy-database#21]
#### Tasks
- [x] Create members modal component
- [x] Add base modal layout (reuse langModal layout)
- [x] Parse Data:
  - [x]  organization, website url, aka, members
- [x] Icons:
  - [x]  website url icon & original document icon
- [x] Layout parsed data as presented in mock-up
