### ISSUE TITLE
Table Styling 

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/tech-policy-database#22]
#### Description
Base styling for the data table. Tasks should be completed through utilizing SASS files and styling by elements. 

#### Tasks
- [x] Add background color to header cells
- [x] Add background color to table cells
- [x] Table Borders:
  - [x] Add Raised divider after the first table column
  - [x] Add horizontal border styling 
  - [x] Remove vertical border styling
